import "../styles/globals.css"
import Head from "next/head"
import { MoralisProvider } from "react-moralis"
import Header from "../components/Header"
import { NotificationProvider } from "web3uikit"
import { ApolloProvider, ApolloClient, InMemoryCache } from "@apollo/client"

// have to initialize the Client
// this client tells graphql where it should making those queries
const client = new ApolloClient({
    // help when we do refresh
    cache: new InMemoryCache(),
    // api of subgraph (thegraph.com => details => )
    // centralized gateway similar to IPFS
    uri: "https://api.studio.thegraph.com/query/37907/nft-marketplace-fcc/v0.0.1",
})

function MyApp({ Component, pageProps }) {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <MoralisProvider initializeOnMount={false}>
                <ApolloProvider client={client}>
                    <NotificationProvider>
                        <Header />
                        <Component {...pageProps} />
                    </NotificationProvider>
                </ApolloProvider>
            </MoralisProvider>
        </>
    )
}

export default MyApp
